### ISSUE TITLE
Can I get the exact location of the problem?

### ISSUE THREAD

**Issue by didebughu** [google/vandalir#15]
As the title
I see that the current problem information output only contains the function name.
Can I get the exact location of the problem? Such as line of problem in the source file
Is there any better way

**Comment by dmitryya** [comment]
I am open to proposition, but keep in mind that LLVM-IR does not have information about "source file".
The best thing I can do now is to provide: function name, block name (or id), instruction offset in the block (or global instruction id), LLVM IR reconstructed instruction and problematic vreg name.

**Comment by didebughu** [comment]
I have made some progress：
Source code line counts can be mapped into LLVM IR files with debug information
such as:
clang example.c -c -emit-llvm -g

And llvm_ir provide [DebugLoc](https://docs.rs/llvm-ir/0.8.2/llvm_ir/debugloc/struct.DebugLoc.html#)
vandalir can get line through methods like
.........................
let loc = func.get_debug_loc();

**Comment by didebughu** [comment]
I created a fork and experimented with let souffle to output the line

**Comment by dmitryya** [comment]
feel free to send a pull request.
