### ISSUE TITLE
cargo build failed on macOS

### ISSUE THREAD

**Issue by didebughu** [google/vandalir#5]
when I run "cargo build --release",  it breaks with the following error

error: failed to run custom build command for `llvm-sys v140.0.5`

Caused by:
  process didn't exit successfully: `/Users/albert/tool/vandalir/target/release/build/llvm-sys-9fa226346e4bfaf1/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_SYS_140_PREFIX
  cargo:rerun-if-env-changed=LLVM_SYS_140_IGNORE_BLOCKLIST
  cargo:rerun-if-env-changed=LLVM_SYS_140_STRICT_VERSIONING
  cargo:rerun-if-env-changed=LLVM_SYS_140_NO_CLEAN_CFLAGS
  cargo:rerun-if-env-changed=LLVM_SYS_140_USE_DEBUG_MSVCRT
  cargo:rerun-if-env-changed=LLVM_SYS_140_FFI_WORKAROUND
  TARGET = Some("x86_64-apple-darwin")
......
......
--- stderr
  thread 'main' panicked at 'system library flag "/usr/local/lib/libz3.dylib" does not look like a link library', /Users/albert/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-140.0.5/build.rs:257:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by dmitryya** [comment]
Interesting...
Good finding. Thank you.

**Comment by dmitryya** [comment]
Could you try:
```
brew install llvm@14
export LLVM_SYS_140_PREFIX=/usr/local/Cellar/llvm@14/14.0.6
```

**Comment by didebughu** [comment]
Thanks a lot!
I build successfully after install llvm@14 and export.

**Comment by didebughu** [comment]
Thanks a lot!
I build successfully after install llvm@14 and export.
